### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by wimdeblauwe** [BitWeb/bitweb-ogone#2]
Will there be a release of this code? I could use it for a project of mine.

**Comment by tobre6** [comment]
Release done. Thank you.

**Comment by wimdeblauwe** [comment]
Will it be on Maven central?

**Comment by tobre6** [comment]
Done.

**Comment by wimdeblauwe** [comment]
Great. What are the coordinates?

**Comment by taavisikk** [comment]
It will take a couple of days to be approved by them and then we can deploy it to their repo.

**Comment by taavisikk** [comment]
http://search.maven.org/#artifactdetails|ee.bitweb|bitweb-ogone|1.0.1|jar
